server:
  port: 8888
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id:

kafka:
  topics:
    users-topic: users-topic