server:
  port: 8888
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
kafka:
  topics:
    users-topic: users-topic